### ISSUE TITLE
"Are you trying to mount a directory onto a file (or vice-versa)?" error when creating container

### ISSUE THREAD

**Issue by roynuj** [madnuttah/unbound-docker#23] opened 2023-04-28 05:20 UTC
I'm trying to use this container for the first time and I'm running into an error after running "docker-compose up -d":

> Creating unbound ... error
> 

> ERROR: for unbound  Cannot start service unbound: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/containers/pihole-new/unbound/unbound.conf" to rootfs at "/usr/local/unbound/unbound.conf": mount /home/pi/containers/pihole-new/unbound/unbound.conf:/usr/local/unbound/unbound.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
> 
> ERROR: for unbound  Cannot start service unbound: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/containers/pihole-new/unbound/unbound.conf" to rootfs at "/usr/local/unbound/unbound.conf": mount /home/pi/containers/pihole-new/unbound/unbound.conf:/usr/local/unbound/unbound.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

It looks like unbound.conf is being created as a directory instead of a file (and note that everything is using root:root instead of pi:pi):

> pi@pi-eloh:~/containers/pihole-new $ ls -la unbound
> total 28
> drwxr-xr-x 7 root root 4096 Apr 27 22:16 .
> drwxr-xr-x 5 pi   pi   4096 Apr 27 22:16 ..
> drwxr-xr-x 2 root root 4096 Apr 27 22:16 conf.d
> drwxr-xr-x 2 root root 4096 Apr 27 22:16 iana.d
> drwxr-xr-x 3 root root 4096 Apr 27 22:16 log.d
> drwxr-xr-x 2 root root 4096 Apr 27 22:16 unbound.conf
> drwxr-xr-x 2 root root 4096 Apr 27 22:16 zones.d

If I manually remove unbound.conf, then touch it to create a file, I get an error for the log.d/unbound.log, which is also a directory and not a file:

> Creating unbound ... error
> 
> ERROR: for unbound  Cannot start service unbound: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/containers/pihole-new/unbound/log.d/unbound.log" to rootfs at "/usr/local/unbound/log.d/unbound.log": mount /home/pi/containers/pihole-new/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
> 
> ERROR: for unbound  Cannot start service unbound: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/containers/pihole-new/unbound/log.d/unbound.log" to rootfs at "/usr/local/unbound/log.d/unbound.log": mount /home/pi/containers/pihole-new/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
> ERROR: Encountered errors while bringing up the project.

Manually changing both of these directories to files allows the container to start.  I checked the Dockerfile and it's not obvious to me why these are being created as directories and not files.

**Comment by madnuttah** [comment] 2023-04-28 05:32
It looks like the filesystem isn't mounted properly via fstab.

Could you provide your docker compose and fstab, please?

**Comment by roynuj** [comment] 2023-04-28 05:37
Here you go:

```
pi@pi-eloh:~/containers/pihole-new $ cat /etc/fstab
proc            /proc           proc    defaults          0       0
PARTUUID=1534a318-01  /boot           vfat    defaults          0       2
PARTUUID=1534a318-02  /               ext4    defaults,noatime  0       1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that
```

[docker-compose.yml.txt](https://github.com/madnuttah/unbound-docker/files/11350272/docker-compose.yml.txt)

**Comment by madnuttah** [comment] 2023-04-28 06:02
Can you show the output with ls -la of the unbound dir? Is the persistent volume mapped directly or via share? User and group 1000 needs permissions, too.

**Comment by roynuj** [comment] 2023-04-28 06:16
I believe the persistent volume is mapped directly.  How could I tell?

Here's the default directory structure on a fresh docker-compose up -d:

```
pi@pi-eloh:~/containers/pihole-new $ ls -laR unbound
unbound:
total 28
drwxr-xr-x 7 root root 4096 Apr 27 23:16 .
drwxr-xr-x 6 pi   pi   4096 Apr 27 23:16 ..
drwxr-xr-x 2 root root 4096 Apr 27 23:16 conf.d
drwxr-xr-x 2 root root 4096 Apr 27 23:16 iana.d
drwxr-xr-x 3 root root 4096 Apr 27 23:16 log.d
drwxr-xr-x 2 root root 4096 Apr 27 23:16 unbound.conf
drwxr-xr-x 2 root root 4096 Apr 27 23:16 zones.d

unbound/conf.d:
total 8
drwxr-xr-x 2 root root 4096 Apr 27 23:16 .
drwxr-xr-x 7 root root 4096 Apr 27 23:16 ..

unbound/iana.d:
total 8
drwxr-xr-x 2 root root 4096 Apr 27 23:16 .
drwxr-xr-x 7 root root 4096 Apr 27 23:16 ..

unbound/log.d:
total 12
drwxr-xr-x 3 root root 4096 Apr 27 23:16 .
drwxr-xr-x 7 root root 4096 Apr 27 23:16 ..
drwxr-xr-x 2 root root 4096 Apr 27 23:16 unbound.log

unbound/log.d/unbound.log:
total 8
drwxr-xr-x 2 root root 4096 Apr 27 23:16 .
drwxr-xr-x 3 root root 4096 Apr 27 23:16 ..

unbound/unbound.conf:
total 8
drwxr-xr-x 2 root root 4096 Apr 27 23:16 .
drwxr-xr-x 7 root root 4096 Apr 27 23:16 ..

unbound/zones.d:
total 8
drwxr-xr-x 2 root root 4096 Apr 27 23:16 .
drwxr-xr-x 7 root root 4096 Apr 27 23:16 ..
```

**Comment by madnuttah** [comment] 2023-04-28 06:22
This is the output of my unbound directory:

```
total 7
drwxrwxrwx    2 1000     1000             0 Apr 25 17:02 .
drwxr-xr-x    5 root     root          4096 Feb  3 17:11 ..
drwxrwxrwx    2 1000     1000             0 Apr 24 14:00 conf.d
drwxrwxrwx    2 1000     1000             0 Apr 28 08:05 iana.d
drwxrwxrwx    2 1000     1000             0 Apr 28 07:42 log.d
-rwxrwxrwx    1 1000     1000           294 Jan  3  2022 unbound.conf
drwxrwxrwx    2 1000     1000             0 Dec 13 16:42 zones.d
```

Edit: and from within unbound container:

```
/usr/local/unbound # ls -la
total 32
drwxr-xr-x    1 _unbound _unbound      4096 Apr 17 11:53 .
drwxr-xr-x    1 root     root          4096 Apr 17 11:53 ..
drwxr-xr-x    2 _unbound _unbound      4096 Apr 17 11:53 certs.d
drwxrwxrwx    2 _unbound _unbound         0 Apr 24 14:00 conf.d
drwxrwxrwx    2 _unbound _unbound         0 Apr 28 08:05 iana.d
drwxr-xr-x    1 _unbound _unbound      4096 Apr 25 17:35 log.d
-rwxrwxrwx    1 _unbound _unbound       294 Jan  3  2022 unbound.conf
drwxr-xr-x    1 _unbound _unbound      4096 Apr 27 19:05 unbound.d
drwxrwxrwx    2 _unbound _unbound         0 Dec 13 16:42 zones.d
```


Your folder permissions doesn't seem right. Can you try to fix them?

**Comment by roynuj** [comment] 2023-04-28 06:47
They're created as root when the unbound directory is created by running "docker-compose up".  I can manually change them, but I would have hoped that the Dockerfile would create them with the correct permissions.  Note that this doesn't help the fact that unbound.conf and log.d/unbound.conf are created as directories.

If I manually changed unbound.conf and log.d/unbound.conf to files instead of directories, the container starts without issues.

For a bit more context, a few folks are running into this using the instructions from https://www.xfelix.com/2020/09/pihole-unbound-docker-setup-on-raspberry-pi/ (see the comments section at the bottom of the page).

**Comment by madnuttah** [comment] 2023-04-28 06:55
So it works if you set the correct permissions? The creation of the directories and setting of the permissions is done in the dockerfile, the _unbound user has the uid/gid 1000. Please add your "root" user to gid 1000 for testing.

**Comment by madnuttah** [comment] 2023-04-28 07:23
It's quite common to fix permissions to make containers run, btw.

**Comment by broomwalker** [comment] 2023-04-28 14:04
@roynuj, did you actually get it working. Also following that guide and just doesn’t work.
I’m thinking this Pihole + Unbound docker idea is a little light on documentation everywhere, unless you’re proficient at all this… full of land mines if you aren’t.

**Comment by madnuttah** [comment] 2023-04-28 15:28
Please comment out the volume mappings in your compose file. Does the container start?

**Comment by roynuj** [comment] 2023-04-28 15:41
@madnuttah Yes, it starts right up with the volume mappings commented out.

@broomwalker I got the container started, but I haven't gotten unbound to serve DNS results to pihole yet.

**Comment by madnuttah** [comment] 2023-04-28 15:54
Please use this command, uncomment your volumes and try to start the container again: 

`sudo chown -R root:1000 /home/pi/unbound/`

**Comment by roynuj** [comment] 2023-04-28 16:47
Same error starting the container.  unbound.conf is still a directory, not a file.

**Comment by madnuttah** [comment] 2023-04-28 16:58
Please run the following command and try to start the container:

`sudo wget https://raw.githubusercontent.com/madnuttah/unbound-docker/main/unbound/root/usr/local/unbound/unbound.conf -P /home/pi/unbound/`

Edit: sorry, linked the wrong conf

**Comment by roynuj** [comment] 2023-04-29 02:53
Now log.d/unbound.log is problematic because it's still a directory.

```
pi@pi-eloh:~/containers/pihole-new $ mkdir unbound
pi@pi-eloh:~/containers/pihole-new $ sudo wget https://raw.githubusercontent.com/madnuttah/unbound-docker/main/unbound/root/usr/local/unbound/unbound.conf -P unbound/
--2023-04-28 19:51:50--  https://raw.githubusercontent.com/madnuttah/unbound-docker/main/unbound/root/usr/local/unbound/unbound.conf
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52162 (51K) [text/plain]
Saving to: 'unbound/unbound.conf'

unbound.conf                                                                  100%[===============================================================================================================================================================================================>]  50.94K  --.-KB/s    in 0.009s  

2023-04-28 19:51:50 (5.36 MB/s) - 'unbound/unbound.conf' saved [52162/52162]

pi@pi-eloh:~/containers/pihole-new $ sudo chown -R root:1000 unbound
pi@pi-eloh:~/containers/pihole-new $ ls -laR unbound
unbound:
total 60
drwxr-xr-x 2 root pi  4096 Apr 28 19:51 .
drwxr-xr-x 6 pi   pi  4096 Apr 28 19:51 ..
-rw-r--r-- 1 root pi 52162 Apr 28 19:51 unbound.conf
pi@pi-eloh:~/containers/pihole-new $ docker-compose up -d unbound
Removing unbound
Recreating c98ea9f9069d_unbound ... error

ERROR: for c98ea9f9069d_unbound  Cannot start service unbound: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/containers/pihole-new/unbound/log.d/unbound.log" to rootfs at "/usr/local/unbound/log.d/unbound.log": mount /home/pi/containers/pihole-new/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for unbound  Cannot start service unbound: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/containers/pihole-new/unbound/log.d/unbound.log" to rootfs at "/usr/local/unbound/log.d/unbound.log": mount /home/pi/containers/pihole-new/unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
pi@pi-eloh:~/containers/pihole-new $ ls -laR unbound
unbound:
total 76
drwxr-xr-x 6 root pi    4096 Apr 28 19:52 .
drwxr-xr-x 6 pi   pi    4096 Apr 28 19:51 ..
drwxr-xr-x 2 root root  4096 Apr 28 19:52 conf.d
drwxr-xr-x 2 root root  4096 Apr 28 19:52 iana.d
drwxr-xr-x 3 root root  4096 Apr 28 19:52 log.d
-rw-r--r-- 1 root pi   52162 Apr 28 19:51 unbound.conf
drwxr-xr-x 2 root root  4096 Apr 28 19:52 zones.d

unbound/conf.d:
total 8
drwxr-xr-x 2 root root 4096 Apr 28 19:52 .
drwxr-xr-x 6 root pi   4096 Apr 28 19:52 ..

unbound/iana.d:
total 8
drwxr-xr-x 2 root root 4096 Apr 28 19:52 .
drwxr-xr-x 6 root pi   4096 Apr 28 19:52 ..

unbound/log.d:
total 12
drwxr-xr-x 3 root root 4096 Apr 28 19:52 .
drwxr-xr-x 6 root pi   4096 Apr 28 19:52 ..
drwxr-xr-x 2 root root 4096 Apr 28 19:52 unbound.log

unbound/log.d/unbound.log:
total 8
drwxr-xr-x 2 root root 4096 Apr 28 19:52 .
drwxr-xr-x 3 root root 4096 Apr 28 19:52 ..

unbound/zones.d:
total 8
drwxr-xr-x 2 root root 4096 Apr 28 19:52 .
drwxr-xr-x 6 root pi   4096 Apr 28 19:52 ..
pi@pi-eloh:~/containers/pihole-new $ 
```

**Comment by madnuttah** [comment] 2023-04-29 06:04
Please run `sudo touch /home/pi/unbound/log.d/unbound.log` and then `sudo chown -R root:1000 /home/pi/unbound/` again.

The container spins up?

**Comment by roynuj** [comment] 2023-04-29 06:07
If I remove the "./log.d/unbound.log/" directory created by the Dockerfile, then manually create the file and give it the correct permissions, yes, the container starts up.

**Comment by madnuttah** [comment] 2023-04-29 06:09
I'll refine my documentation. If the issue is fixed, please close the issue.

Thanks for your patience and cooperation.

**Comment by madnuttah** [comment] 2023-04-29 06:11
I'm here and glad to help if you need further assistance.

**Comment by roynuj** [comment] 2023-04-29 06:15
I can’t really say it’s resolved since it doesn’t work with the Dockerfile as is. Yes, we’ve identified a workaround. Is there a way I can help identify the root cause so a workaround isn’t needed?

**Comment by madnuttah** [comment] 2023-04-29 06:19
That's no workaround, the files are there as they should be now. 

Sure, there's more to do to make unbound resolve. When this particular issue is resolved by your side, please close it and open a new one to keep the issues clean.

Thanks. We'll get the rest running, too.

**Comment by madnuttah** [comment] 2023-04-29 07:20
@roynuj I think the problem with the files occurs as soon as no **mounted** persistent volume is used, I didn't read about this file/directory problem until now as the most people use mounted volumes. I'll update my documentation. May @x-Felix will adapt his instructions, too.

I hope this fixes the problems @broomwalker had as well.

**Closed as completed** 2023-04-29 17:19 UTC

**Comment by x-Felix** [comment] 2023-05-01 03:05
Hi @madnuttah , apologise to reply this closed issue. But I do see some potential issues with the file permissions. 
When starts, it complains unbound.log permission issue. When dig some domain for testing, it complains root.key permission then keep restarting the service. 
If I quote out the file path in conf file, line #4 of [logging.conf](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/usr/local/unbound/conf.d/logging.conf), and line #2 of [trust-anchor.conf](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/usr/local/unbound/conf.d/trust-anchor.conf) , the unbound can start successfully without any issue. 
Not sure whether those example conf duplicate with https://github.com/madnuttah/unbound-docker/blob/main/unbound/root/usr/local/unbound/unbound.conf that causing issue? I also have no idea why my existing running instance does not have those issue. It can be reproduced on a brand new implementation.

**Comment by madnuttah** [comment] 2023-05-02 04:50
Compose won't copy files to persistent volumes, you have to put the files there first and fix permissions.

The default unbound.conf should always work, after this is verified, you can extract sections from the config and put it into separate confs.

How's the permissions for root.key? These should be set correctly already.

I guess you set up with the default conf first and afterwards structuring your configs.

**Comment by x-Felix** [comment] 2023-05-02 07:44
@madnuttah I just test with the example configs. If map the iana.d volume and use the example config which pointing the root.key file path, the container will keep restarting once receive first query. And the log complains root.key-random characters cannot write to iana.d. If I quote out the root.key path from config file, the container can successfully start and create root.key to mapped iana.d without issue.

**Comment by madnuttah** [comment] 2023-05-02 07:48
Can you download the root.key to iana.d and set permissions to test?

**Comment by x-Felix** [comment] 2023-05-02 08:32
I did that. I created an initial root.key file in that folder with permission same as iana.d directory. Owned by pi:pi user. When container starts, after receiving first query. It complains the same error reading writing to iana.d/root.key and keeps restarting. When checking the iana.d directory, the root.key content gets updated, and permission changes to root:root.

**Comment by madnuttah** [comment] 2023-05-02 09:09
Those permissions seem right to me. Can you put the root user in group 1000 please for testing?

**Comment by x-Felix** [comment] 2023-05-03 02:57
I tested it again with the example config files. [logging.conf](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/usr/local/unbound/conf.d/logging.conf) and [trust-anchor.conf](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/usr/local/unbound/conf.d/trust-anchor.conf) has the log file and root.key path pointed. 
The unbound/log.d is empty and unbound/iana.d only has root.zone. 
I then run `sudo chown -R root:1000 /home/pi/unbound/` . The file permission shows root:opc after the change. 
Start the container without any issues. But notice, unbound/log.d/unbound.log and unbound/iana.d/root.key ownership is opc:opc . All other files remain ownership root:opc.

**Comment by madnuttah** [comment] 2023-05-03 04:49
As I wrote earlier, this is a bit of a special setup as most people use persistent folders mapped from a NAS. The opc user has the gid 1000 which makes the container able to start due to correct permissions.

**Comment by rmorsilva** [comment] 2024-01-16 02:40
> I tested it again with the example config files. [logging.conf](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/usr/local/unbound/conf.d/logging.conf) and [trust-anchor.conf](https://github.com/madnuttah/unbound-docker/blob/main/unbound/examples/usr/local/unbound/conf.d/trust-anchor.conf) has the log file and root.key path pointed. The unbound/log.d is empty and unbound/iana.d only has root.zone. I then run `sudo chown -R root:1000 /home/pi/unbound/` . The file permission shows root:opc after the change. Start the container without any issues. But notice, unbound/log.d/unbound.log and unbound/iana.d/root.key ownership is opc:opc . All other files remain ownership root:opc.

Hi everyone!
I know this issue is basically dead but recently I tried installing unbound on docker and I had the exact same problems as @x-Felix.

Example:
Permissions of “unbound/iana.d” before I ran the dig command (dig [http://www.google.com](https://www.google.com/) @172.20.0.7 -p 5335):

drwxr-xr-x 2 root pi 4096 Jan 16 02:16 .
drwxr-xr-x 6 root pi 4096 Jan 16 01:16 ..
-rw-r–r– 1 root pi 758 Jan 16 02:16 root.key
-rwxr-xr-x 1 root pi 2254606 Jan 15 19:10 root.zone

Permissions of “unbound/iana.d” after I ran the dig command:

drwxr-xr-x 2 root pi 4096 Jan 16 02:24 .
drwxr-xr-x 6 root pi 4096 Jan 16 01:16 ..
-rw-r–r– 1 root root 758 Jan 16 02:24 root.key
-rwxr-xr-x 1 root pi 2254606 Jan 15 19:10 root.zone

Is there any solution for this or still not?

Thank you in advance for your help

**Comment by madnuttah** [comment] 2024-01-16 11:29
As this issue is closed, please open a new one, I'm glad to help.
